document.querySelectorAll(".nav-link").forEach((link) => {
  if (link.href === window.location.href) {
    link.classList.add("active");
    link.setAttribute("aria-current", "page");
  }
});

const products = [
  // CHIP&KURKURE------------------------------->>>>
  {
    id: 1,
    name: "Lays All Dressed",
    category: "chips & kurkure",
    price: "₹25.00",
    rating: "4.5",
    image: "./assets/chips/allDressed.png",
    description: "Combination of all flavour",
  },
  {
    id: 2,
    name: "Lays Sour Cream",
    category: "chips & kurkure",
    price: "₹20.00",
    rating: "4.5",
    image: "./assets/chips/sour-cream.png",
    description: "Sour Cream Potato Chips",
  },
  {
    id: 3,
    name: "Lays Classic Salt",
    category: "chips & kurkure",
    price: "₹10.00",
    rating: "4.5",
    image: "./assets/chips/laysclassicsalt.png",
    description: "Salty Taste potato Chips",
  },
  {
    id: 4,
    name: "Lays BBQ",
    category: "chips & kurkure",
    price: "₹25.00",
    rating: "4.5",
    image: "./assets/chips/lays1.png",
    description: "Spicy Sweetness Of BBQ Sauce",
  },
  {
    id: 5,
    name: "Lays Cream & Oninon",
    category: "chips & kurkure",
    price: "₹10.00",
    rating: "4.5",
    image: "./assets/chips/layscreamnonion.png",
    description: "Creamy Potato Chips Sauce",
  },
  {
    id: 6,
    name: "Lays Sour & Onion Cream",
    category: "chips & kurkure",
    price: "₹20.00",
    rating: "4.5",
    image: "./assets/chips/sour-cream.png",
    description: "Sour Cream & Onion Potato Chips",
  },
  {
    id: 7,
    name: "Kurkure PuffCorn",
    category: "chips & kurkure",
    price: "₹10.00",
    rating: "4.5",
    image: "./assets/chips/puffcorn.png",
    description: "Chess Flavour CornPuff",
  },
  {
    id: 8,
    name: "Kurkure Masala Munch",
    category: "chips & kurkure",
    price: "₹10.00",
    rating: "4.5",
    image: "./assets/chips/kurkure1.png",
    description: "Crispy & Crunchy",
  },
  {
    id: 9,
    name: "Uncle Chipps",
    category: "chips & kurkure",
    price: "₹20.00",
    rating: "4.5",
    image: "./assets/chips/unclechips1.png",
    description: "Crispy & Tasty Masala",
  },
  {
    id: 10,
    name: "Bingo",
    category: "chips & kurkure",
    price: "₹10.00",
    rating: "4.5",
    image: "./assets/chips/bingo.png",
    description: "Crispy & Chilli",
  },
  {
    id: 11,
    name: "Lays Flaming Hot",
    category: "chips & kurkure",
    price: "₹20.00",
    rating: "4.5",
    image: "./assets/chips/LaysFlaminHot.png",
    description: "Chilli & Sweeet",
  },

  // DRINKS------------------------------------------>>>>
  {
    id: 12,
    name: "Coca-Cola",
    category: "drinks",
    quantity: "1L",
    price: "₹50.00",
    rating: "4.5",
    image: "./assets/drinks/cocacolaBottle.png",
    description: "",
  },
  {
    id: 13,
    name: "Coconut Water",
    category: "drinks",
    quantity: "1L",
    price: "₹100.00",
    rating: "4.5",
    image: "./assets/drinks/cocnutWater.png",
    description: "Sweet Coconut water",
  },
  {
    id: 14,
    name: "Coke Can",
    category: "drinks",
    quantity: "200ml",
    price: "₹70.00",
    rating: "4.5",
    image: "./assets/drinks/cokeCan.png",
    description: "Soft Drink Zero Sugar",
  },
  {
    id: 15,
    name: "ColdBerg",
    category: "drinks",
    quantity: "330ml",
    price: "₹80.00",
    rating: "4.5",
    image: "./assets/drinks/coldBerg.png",
    description: "Cranerbery Non Alcoholic Beer",
  },
  {
    id: 16,
    name: "Dew",
    category: "drinks",
    quantity: "400ml",
    price: "₹40",
    rating: "4.5",
    image: "./assets/drinks/dew.png",
    description: "Citrus Soft Drink",
  },
  {
    id: 17,
    name: "Frooti",
    category: "drinks",
    quantity: "1.8L",
    price: "₹50.00",
    rating: "4.5",
    image: "./assets/drinks/frootiBottle.png",
    description: "Mango Fruit juice",
  },
  {
    id: 18,
    name: "Real Juice",
    category: "drinks",
    quantity: "1L",
    price: "₹120.00",
    rating: "4.5",
    image: "./assets/drinks/juice.png",
    description: "Mixed Fruit Juice",
  },
  {
    id: 19,
    name: "Limca",
    category: "drinks",
    quantity: "500ml",
    price: "₹40.00",
    rating: "4.5",
    image: "./assets/drinks/limca.png",
    description: "",
  },
  {
    id: 20,
    name: "Pepsi",
    category: "drinks",
    quantity: "500ml",
    price: "₹50.00",
    rating: "4.5",
    image: "./assets/drinks/pepsiBottle.png",
    description: "",
  },
  {
    id: 21,
    name: "RedBull",
    category: "drinks",
    quantity: "250ml",
    price: "₹120",
    rating: "4.5",
    image: "./assets/drinks/redbull.png",
    description: "Energy Drink",
  },
  {
    id: 22,
    name: "Sprite",
    category: "drinks",
    quantity: "500ml",
    price: "₹40.00",
    rating: "4.5",
    image: "./assets/drinks/sprite.png",
    description: "Lemon & Lime Soft Drink",
  },
  {
    id: 23,
    name: "ThumsUp",
    category: "drinks",
    quantity: "500ml",
    price: "₹40.00",
    rating: "4.5",
    image: "./assets/drinks/thumsUp.png",
    description: "Soft Drink",
  },
  {
    id: 24,
    name: "Bisleri Water Bottle",
    category: "drinks",
    quantity: "1L",
    price: "₹20.00",
    rating: "4.5",
    image: "./assets/drinks/water1L.png",
    description: "Purified Water",
  },

  // FRUITS----------------------------------------->>>>
  {
    id: 25,
    name: " Apple",
    category: "fruits",
    quantity: "5PC (500gm)",
    price: "₹220.00",
    rating: "4.5",
    image: "./assets/fruits/apple.png",
  },
  {
    id: 26,
    name: "Banana",
    category: "fruits",
    quantity: "500gm",
    price: "₹100.00",
    rating: "4.5",
    image: "./assets/fruits/banana.png",
  },
  {
    id: 27,
    name: "Coconut",
    category: "fruits",
    quantity: "1Pc",
    price: "₹100.00",
    rating: "4.5",
    image: "./assets/fruits/coconut.png",
  },
  {
    id: 28,
    name: "Dragon Fruit",
    category: "fruits",
    quantity: "1Pc",
    price: "₹150.00",
    rating: "4.5",
    image: "./assets/fruits/dragonFruit.png",
  },
  {
    id: 29,
    name: "Red Grapes",
    category: "fruits",
    quantity: "200gm",
    price: "₹100.00",
    rating: "4.5",
    image: "./assets/fruits/grapes.png",
  },
  {
    id: 30,
    name: "Kiwi",
    category: "fruits",
    quantity: "3Pc",
    price: "₹100.00",
    rating: "4.5",
    image: "./assets/fruits/kiwi.png",
  },
  {
    id: 31,
    name: "Orange",
    category: "fruits",
    quantity: "500gm",
    price: "₹130.00",
    rating: "4.5",
    image: "./assets/fruits/orange.png",
  },
  {
    id: 32,
    name: "Pear",
    category: "fruits",
    quantity: "2Pc",
    price: "₹100.00",
    rating: "4.5",
    image: "./assets/fruits/pear.png",
  },
  {
    id: 33,
    name: "Pineapple",
    category: "fruits",
    quantity: "200gm",
    price: "₹70.00",
    rating: "4.5",
    image: "./assets/fruits/pineapple.png",
  },
  {
    id: 34,
    name: "Pomegranate",
    category: "fruits",
    quantity: "4Pc (700gm)",
    price: "₹250.00",
    rating: "4.5",
    image: "./assets/fruits/pomegranate.png",
  },
  {
    id: 35,
    name: "Watermelon",
    category: "fruits",
    quantity: "250gm",
    price: "₹40.00",
    rating: "4.5",
    image: "./assets/fruits/waterMelon.png",
  },

  // VEGITABLE-------------------------------------->>>>
  {
    id: 36,
    name: "Beans",
    category: "vegitable",
    quantity: "25gm",
    price: "₹24.00",
    rating: "4.5",
    image: "./assets/vegitables/beans.png",
  },
  {
    id: 37,
    name: "Mushroom",
    category: "vegitable",
    quantity: "200gm",
    price: "₹60.00",
    rating: "4.5",
    image: "./assets/vegitables/mushroom.png",
  },
  {
    id: 38,
    name: "Capsicum",
    category: "vegitable",
    quantity: "2Pc",
    price: "₹30.00",
    rating: "4.5",
    image: "./assets/vegitables/capsicum.png",
  },
  {
    id: 39,
    name: "Beetroot",
    category: "vegitable",
    quantity: "500gm",
    price: "₹27.00",
    rating: "4.5",
    image: "./assets/vegitables/beetroot.png",
  },
  {
    id: 40,
    name: "Bitter Gourd",
    category: "vegitable",
    quantity: "500gm",
    price: "₹30.00",
    rating: "4.5",
    image: "./assets/vegitables/bittergourd.png",
  },
  {
    id: 41,
    name: "Brinjal",
    category: "vegitable",
    quantity: "2Pc",
    price: "₹40.00",
    rating: "4.5",
    image: "./assets/vegitables/brinjal.png",
  },
  {
    id: 42,
    name: "Cabbage",
    category: "vegitable",
    quantity: "600gm",
    price: "₹21.00",
    rating: "4.5",
    image: "./assets/vegitables/cabbage.png",
  },
  {
    id: 43,
    name: "Carrot",
    category: "vegitable",
    quantity: "500gm",
    price: "₹50.00",
    rating: "4.5",
    image: "./assets/vegitables/carrot.png",
  },
  {
    id: 44,
    name: "Cauliflower",
    category: "vegitable",
    quantity: "300gm",
    price: "₹30.00",
    rating: "4.5",
    image: "./assets/vegitables/cauliflower.png",
  },
  {
    id: 45,
    name: "Coriander",
    category: "vegitable",
    quantity: "100gm",
    price: "₹85.00",
    rating: "4.5",
    image: "./assets/vegitables/coriander.png",
  },
  {
    id: 46,
    name: "Cucumber",
    category: "vegitable",
    quantity: "500gm",
    price: "₹50.00",
    rating: "4.5",
    image: "./assets/vegitables/cucumber.png",
  },
  {
    id: 47,
    name: "Curry Leave",
    category: "vegitable",
    quantity: "50gm",
    price: "₹10.00",
    rating: "4.5",
    image: "./assets/vegitables/curryLeave.png",
  },
  {
    id: 48,
    name: "Garlic",
    category: "vegitable",
    quantity: "200gm",
    price: "₹36.00",
    rating: "4.5",
    image: "./assets/vegitables/garlic.png",
  },
  {
    id: 49,
    name: "Ginger",
    category: "vegitable",
    quantity: "150gm",
    price: "₹23.00",
    rating: "4.5",
    image: "./assets/vegitables/ginger.png",
  },
  {
    id: 50,
    name: "Green Chilli",
    category: "vegitable",
    quantity: "100gm",
    price: "₹31",
    rating: "4.5",
    image: "./assets/vegitables/greenChilli.png",
  },
  {
    id: 51,
    name: "Green Peas",
    category: "vegitable",
    quantity: "200gm",
    price: "₹120",
    rating: "4.5",
    image: "./assets/vegitables/greenPeas.png",
  },
  {
    id: 52,
    name: "Lady Finger",
    category: "vegitable",
    quantity: "500gm",
    price: "₹33.00",
    rating: "4.5",
    image: "./assets/vegitables/ladyFinger.png",
  },
  {
    id: 53,
    name: "Onion",
    category: "vegitable",
    quantity: "1Kg",
    price: "₹40.00",
    rating: "4.5",
    image: "./assets/vegitables/onion.png",
  },
  {
    id: 54,
    name: "Potato",
    category: "vegitable",
    quantity: "1Kg",
    price: "₹40.00",
    rating: "4.5",
    image: "./assets/vegitables/potato.png",
  },
  {
    id: 55,
    name: "Pumpkin",
    category: "vegitable",
    quantity: "500gm",
    price: "₹45.00",
    rating: "4.5",
    image: "./assets/vegitables/pumpkin.png",
  },
  {
    id: 56,
    name: "Radish",
    category: "vegitable",
    quantity: "250gm",
    price: "₹13.00",
    rating: "4.5",
    image: "./assets/vegitables/radish.png",
  },
  {
    id: 57,
    name: "Red&Yellow Mushroom",
    category: "vegitable",
    quantity: "3PC (450gm)",
    price: "₹120.00",
    rating: "4.5",
    image: "./assets/vegitables/red_yellow.png",
  },
  {
    id: 58,
    name: "Spinach",
    category: "vegitable",
    quantity: "250gm",
    price: "₹30.00",
    rating: "4.5",
    image: "./assets/vegitables/spinach.png",
  },
  {
    id: 59,
    name: "Tomato",
    category: "vegitable",
    quantity: "250gm",
    price: "₹30.00",
    rating: "4.5",
    image: "./assets/vegitables/toomato.png",
  }, 
];


const productContainer = document.querySelector(".product_item");

function renderProducts(productList) {
  productContainer.innerHTML = "";

  if (productList.length === 0) {
    productContainer.innerHTML = `<p style="grid-column:1 / -1; text-align:center;">No Product Found</p>`;
    return;
  }

  productList.forEach((product) => {
    const box = document.createElement("div");
    box.classList.add("box-items");

    box.innerHTML = `
      <div class="img">
        <img src="${product.image}" alt="${product.name}" 
             onerror="this.src='https://via.placeholder.com/150'">
      </div>
      <div class="product-buy">
        <h4 class="name">${product.name}</h4>
        <p class="quantity">${product.quantity || ""}</p>
        <h5 class="price">Price: ${product.price} | ⭐ ${product.rating}</h5>
        <p class="discription">${product.description || ""}</p>
      </div>
    `;

    productContainer.appendChild(box);
  });
}

// ✅ Call this once to show all items
renderProducts(products);